language: java
jdk:
- openjdk8
sudo: false
dist: xenial
cache:
  directories:
  - $HOME/.m2
  - $HOME/.gradle
matrix:
  include:
    - name: "Test with postgresql 9.4"
      addons:
        postgresql: '9.4'
    - name: "Test with postgresql 9.5"
      addons:
        postgresql: '9.5'
    - name: "Test with postgresql 9.6"
      addons:
        postgresql: '9.6'
    - name: "Test with postgresql 10.7"
      addons:
        postgresql: "10.7"
        apt:
          packages:
          - postgresql-10
          - postgresql-client-10
      before_install:
        - sudo cp /etc/postgresql/{9.6,10}/main/pg_hba.conf
        - sudo /etc/init.d/postgresql restart
    - name: "Test with postgresql 11.2"
      addons:
        postgresql: "11.2"
      before_install:
        - sudo apt-get update
        - sudo apt-get --yes remove postgresql\*
        - sudo apt-get install -y postgresql-11 postgresql-client-11
        - sudo cp /etc/postgresql/{9.6,11}/main/pg_hba.conf
        - sudo service postgresql restart 11
install: /bin/true
before_script:
- psql -c 'SHOW SERVER_VERSION;' -U postgres
- psql -c 'CREATE DATABASE travis_ci_test;' -U postgres
- ./gradlew spotlessCheck scoverageClasses --info --stacktrace
script:
- export GRADLE_OPTS="-Xmx500m"
- export JAVA_OPTS="-Xmx500m"
after_success:
- ./gradlew reportScoverage coveralls --info --stacktrace
env:
  global:
  - CI_NAME=travis-ci
  - MALLOC_ARENA_MAX=2
  - secure: Ld8TSElGS54hAfrAQZcTWw47chK1lliOpDf7yluExco/K+W1Ddj2UzVrPspRJXCcl6bBZTwE4aosEB0P6EAX4IAQVyKOUvJVN2tlp8tq13/KltWCV7Wt0HWC96kVp4nZv8QpZhT3cyilDDE7h1WgKQY2NXB7JIyQDvO2NROjno0O8Nfi8Jf1/faSnfWqMj2W5Z7p+GIxYXiQS2LxUZ9YpCMrs0cEnL6EjJyVj+LkJgp3exCYNtmbD0jQ5uWxmKJaO1SijfPuztIq4F8SDcikKdOTaLpDvB2tj/aq9x4pcjVG/66TaX8RusVtrkh/L4G4oApAs9AFjXz3PUPqXQQ9e5WrTckrMRaOunPc5K0ajdCw3v6aWwAJyXpdP3M572vSPxn5EQCrOXaLJd+LotDiSTvRDTPvX2uaf3aSB+G405YGoJ6Y+xjZfSngcP8r1Hlnh+eGJ/lmlIvBYuYJeALa8Rmniog3mmhh0iavuLDENWszHOHgooxhcPy8cFI1AklaKgOyAXnbwQYWF+K633GgVD5AZxfGdfpjbvOSsnB+kge6JcxFYXI4z/mL02yckl+nBY7S40Z1rRjtvEkrN6ZbnMOA6dA83kjQfazvR0PxLvZntCsApaNcayrngZpIcvMzkznFGowzcSIFOQNKBKRg3ulgAQsl4WVnwg+WEd1ieY8=
