language: scala
scala:
   - 2.11.7

addons:
  postgresql: "9.4"

before_script:
  - psql -c 'SHOW SERVER_VERSION;' -U postgres
  - psql -c 'CREATE DATABASE travis_ci_test;' -U postgres

script: "sbt clean coverage test"

after_success: "sbt coveralls"