language: scala
scala:
  - 2.11.7
addons:
  postgresql: '9.4'
before_script:
  - psql -c 'SHOW SERVER_VERSION;' -U postgres
  - psql -c 'CREATE DATABASE travis_ci_test;' -U postgres
  - curl -L -o $HOME/.sbt/launchers/0.13.8/sbt-launch.jar http://dl.bintray.com/typesafe/ivy-releases/org.scala-sbt/sbt-launch/0.13.8/sbt-launch.jar
script: sbt clean coverage test
after_success: sbt coveralls
env:
  global:
    secure: fICktYC5w0CBqF1RUvBw/CPvEtLzOyJiwP9+nlMZyRVhURcl8EeCkQmLSEYHo1YRQO1rj34MV3qzXAtu/0je1iYtSNVKFzsqkzrecPBZjVgEfTpe68ip9oN3FH1b+wzRHlDy92ofEBcfXoVWcZCG1j5Ku0jwFtvE8J7GlZIqD/GN6GMgvB1ph9pXB1jaFxV8peWMCSQHQxvA1SXXwl2SPbr2ZWq/Sgn5UxbD4XHbHdu+44IP9l6fd2aBwZBXcal6f2lZY2KK0r4DOwpMABw99tRaJu7MlKklAvOC9uGiLhj1zHiGe05Zst/UvGlFoQnmIhKoNpkbFRoZRcPaNGyGZSNvSZ+N3uEKjnhKXKbriNCl0eoUfzMc80W8FDr4EJ1ZxAmSE2fJWy2VefnWlkLueS4IpXkjurdZ8KEtDiilY4Xyw8ENojZ9mYMqqQI3r+vRxGY1pYFd0tu8V5viXE4pzxXKSr3EyzQVIHQ1U8BXtLVe4fF4PC83052cFaGulCZHqlyENy44hgZxg3tsbHSvhDWDWE1cdrvj4GgyiWHNyR/G+o1DQrOEedx2FXpJkmgmnxuEsMqZlsU1zEUB/B4zjWHNuHrcFe/DNRrZSHsFmB0+GJeeKRLB6vTZF1EKeGpQ0X/skzpi8T8by/p484ZyUkGFfy+dhQ5E6CMFzbr+vMA=
notifications:
  hipchat:
    rooms:
      secure: Hl+WLzrA/ppzz/ycl32cjV8iz3KVXLbQK/xnQWZxZ/CXvo8WmlXaVs5bt/kanXMV546Fqbm2V5IUtm5eYt/BialFMCRuTMgJc52p5LUcoWP8zH9trluYFWfVouyfmXmb7N39GLO4jTxSksmBjxkuDZzLVS2NtQ9zByjuD+LYzIeFgt/PqPD1QRaXl3UfwtMtNvc2UDObPuMAPndAbGkoyGtSiTHH2izCpsk5H3xUCmc/I+IgcDvy7DWdqBz817t5WfPOLn3TTJKSsW1mO8h2wBcrSatOP3n9o0Ctf5BE63LCTr2OGWY8NiV5FesWg8xMjB390N/chDqQCWX9ldXED0PrxqhFOg72RKtcpoLlqe1QZ0mzOEJ18f2q46XO+phg1r/QXmH45nEqnbd/NCak2wSTlOqxjAc8UUGjsri5nHIVZpHtG7G/YQlPlZv6eF0MC56sRL2sRchDR+DZYXXmS94VsViM4pyw6pG67CCZzpXrRvM1tocksaXasdHmVQK+uOIacWctT/aHuP0fbxwTUgWQwTQWbh+OMb4TyhZo+GGCFr2yG9MQkqXW05xQCxgIHoLMIJZF87KHG5axmPhEedVpTDzLpMt2PLdLf6xWsBvJRRoo0OPJRJbJOVOnK1GGQmxFzmjdiaFBAcZEETW+eXocszK2++AVlQcfUCgdVJU=
    template:
      - '%{repository}#%{build_number} (%{branch} - %{commit} : %{author}): %{message}'
