handlers=java.util.logging.ConsoleHandler
java.util.logging.ConsoleHandler.formatter=com.campudus.tableaux.helper.LogFormatter
java.util.logging.ConsoleHandler.level=INFO
.level=INFO
io.vertx.ext.web.level=INFO
io.vertx.level=WARNING
io.vertx.ext.auth.oauth2.impl.OAuth2AuthProviderImpl.level=SEVERE
com.hazelcast.level=INFO
io.netty.util.internal.PlatformDependent.level=SEVERE